# Generated by Django 4.1.3 on 2023-03-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_store_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='retailer_barcode',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
