# Generated by Django 4.1.6 on 2023-02-28 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_retailer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='store_address',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
