# Generated by Django 4.1.6 on 2023-03-07 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user_is_retailer_user_store_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='retailer_id',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
